import { Naves } from "./Nave";


export const dataNaves = [
 new Naves( 1,
    "Star Destroyer",
     "Kuat Drive Yards",
     "Diversas",
     "https://lumiere-a.akamaihd.net/v1/images/Star-Destroyer_ab6b94bb.jpeg?region=0%2C0%2C1600%2C900",
     "Costo variable",
    "El Star Destroyer es una nave de guerra masiva utilizada por el Imperio Galáctico para proyectar su poderío militar en toda la galaxia. Es conocida por su imponente tamaño y su capacidad para llevar a cabo operaciones a gran escala.",
     "Imperio"),
     new Naves(  2,
      "Millennium Falcon",
      "Corporación de Ingeniería Corelliana",
      "Corelliano",
      "https://upload.wikimedia.org/wikipedia/en/8/8d/A_screenshot_from_Star_Wars_Episode_IV_A_New_Hope_depicting_the_Millennium_Falcon.jpg",
      "Costo variable",
      "El Millennium Falcon es una nave espacial modificada YT-1300 que se convirtió en una de las naves más famosas de la galaxia debido a su velocidad y durabilidad. Es propiedad de Han Solo y Chewbacca.",
      "Rebelión"),
     new Naves(  3,
      "X-wing",
      "Incom Corporation",
      "Diversas",
      "https://lumiere-a.akamaihd.net/v1/images/X-Wing-Fighter_47c7c342.jpeg?region=0%2C96%2C1536%2C769",
      "150,000 créditos",
      "El X-wing es un caza estelar de ala en X utilizado por la Alianza Rebelde y más tarde por la Nueva República en su lucha contra el Imperio Galáctico. Es conocido por su versatilidad y capacidad de combate.",
      "Rebelión"),
     new Naves(  4,
      "Death Star",
      "Imperio Galáctico",
      "Diversas",
      "https://lumiere-a.akamaihd.net/v1/images/Death-Star-I-copy_36ad2500.jpeg?region=0%2C0%2C1600%2C900",
      "Costo astronómico",
      "La Estrella de la Muerte es una estación espacial de combate masiva y altamente destructiva construida por el Imperio Galáctico. Es capaz de destruir planetas enteros con un solo disparo de su superláser.",
      "Imperio"),
     new Naves( 5,
      "TIE Fighter",
      "Sienar Fleet Systems",
      "Humano",
      "https://lumiere-a.akamaihd.net/v1/images/vaders-tie-fighter_8bcb92e1.jpeg?region=0%2C147%2C1560%2C878",
      "60,000 créditos",
      "El TIE Fighter es un caza estelar utilizado por el Imperio Galáctico. Es conocido por su diseño distintivo y su velocidad y maniobrabilidad superiores.",
      "Imperio"),
     new Naves(  6,
      "Slave I",
      "Kuat Systems Engineering",
      "Humano",
      "https://images.bigbadtoystore.com/images/p/full/2020/01/3762d250-aea8-441d-8c64-9b8d8e129b20.jpg",
      "Costo variable",
      "Slave I es la nave esclava personal de Boba Fett, un temido cazarrecompensas. Es conocida por su forma distintiva y su arsenal de armas mortales.",
      "Neutral"),
     new Naves(  7,
      "Tantive IV",
      "Corporación Corelliana de Ingeniería",
      "Alderaan",
      "https://lumiere-a.akamaihd.net/v1/images/tantive-rogue-update_5654204f.jpeg?region=0%2C0%2C1200%2C502",
      "Costo desconocido",
      "El Tantive IV es una corbeta corelliana utilizada por la Alianza Rebelde. Es conocida por su papel en la Batalla de Scarif y por transportar los planos de la Estrella de la Muerte.",
      "Rebelión"),
     new Naves(   8,
      "Y-wing",
      "Koensayr Manufacturing",
      "Diversas",
       "https://lumiere-a.akamaihd.net/v1/images/Y-Wing-Fighter_0e78c9ae.jpeg?region=0%2C24%2C1536%2C768",
      "Dato no disponible",
      "El Y-wing es un bombardero utilizado por la Alianza Rebelde en su lucha contra el Imperio Galáctico. Es conocido por su resistencia y capacidad de llevar a cabo ataques precisos.",
      "Rebelión"
   ),
     new Naves(  9,
      "A-wing",
      "Kuat Systems Engineering",
      "Mon Calamari",
      "https://lumiere-a.akamaihd.net/v1/images/screen_shot_2015-05-26_at_5_16a39e17.png?region=0%2C71%2C812%2C457",
      "Dato no disponible",
      "El A-wing es un caza estelar rápido y ágil utilizado por la Alianza Rebelde. Es conocido por su velocidad y capacidad para realizar maniobras evasivas.",
      "Rebelión"),
     new Naves(  10,
      "Mon Calamari Cruiser",
      "Mon Calamari Shipyards",
      "Mon Calamari",
      "https://lumiere-a.akamaihd.net/v1/images/e6d_ia_2581_47f64de7.jpeg?region=254%2C0%2C1426%2C802",
      "Costo desconocido",
      "Los cruceros Mon Calamari son naves de guerra utilizadas por la Alianza Rebelde. Son conocidos por su diseño orgánico y su capacidad para adaptarse a diversas situaciones de combate.",
      "Rebelión"),
];